#!/usr/bin/env python3
# _*_ coding:utf-8 _*_
#题目一：有四个数字：1、2、3、4，能组成多少个互不相同且无重复数字的三位数？各是多少？

for i in range(1,5):
    for n in range(1,5):
        for x in range(1,5):
             y=i*100+n*10+x
             print(y)
print('______________________')


for i in range(1,5):
    for n in range(1,5):
        for x in range(1,5):
             if (i != x) and (i !=n) and (n!=x):
                 print(i,n,x)


#题目2：企业发放的奖金根据利润提成。利润(I)低于或等于10万元时，奖金可提10%；
# 利润高于10万元，低于20万元时，低于10万元的部分按10%提成，高于10万元的部分，可提成7.5%；
# 20万到40万之间时，高于20万元的部分，可提成5%；40万到60万之间时高于40万元的部分，可提成3%；
# 60万到100万之间时，高于60万元的部分，可提成1.5%，高于100万元时，超过100万元的部分按1%提成，从键盘输入当月利润I，求应发放奖金总数？
# 程序分析：请利用数轴来分界，定位。注意定义时需把奖金定义成长整型。

I=int(input("Enter the number of Interest:"))
Award =0
if I >1000000:
    Award = (I-1000000)*0.01+400000*0.015+200000*0.03+200000*0.05+100000*0.075+100000*0.1
elif (I<=1000000) and (I > 600000):
    Award = (I - 600000) * 0.015 + 200000 * 0.03 + 200000 * 0.05 + 100000*0.075+100000*0.1
elif (I<=600000) and (I > 400000):
    Award = (I - 400000)  * 0.03 + 200000 * 0.05 + 100000*0.075+100000*0.1
elif (I<=400000) and (I > 200000):
    Award = (I - 200000)  * 0.05 + 100000*0.075+100000*0.1
elif (I<=200000) and (I > 100000):
    Award = (I - 100000)  * 0.075 + 100000 * 0.1
else:
    Award = I  * 0.1
print("the Award is : ",Award)

#w以上为我的垃圾代码
#——————————————————————银河——————————————————————————

#大神的代码是酱的
i = int(input("insteret:"))
arr = [1000000,600000,4000000,200000,100000,0]
rat = [0.01,0.015,0.03,0.05,0.075,0.1]
r = 0
for idx in range(0,6):
    if i > arr[idx]:
        r += (i-arr[idx])*rat[idx]
        i = arr[idx]
print(r)


# 题目3：一个整数，它加上100后是一个完全平方数，再加上168又是一个完全平方数，请问该数是多少？
#
# 程序分析：
# 假设该数为 x。
# 1、则：x + 100 = n2, x + 100 + 168 = m2
# 2、计算等式：m2 - n2 = (m + n)(m - n) = 168
# 3、设置： m + n = i，m - n = j，i * j =168，i 和 j 至少一个是偶数
# 4、可得： m = (i + j) / 2， n = (i - j) / 2，i 和 j 要么都是偶数，要么都是奇数。
# 5、从 3 和 4 推导可知道，i 与 j 均是大于等于 2 的偶数。
# 6、由于 i * j = 168， j>=2，则 1 < i < 168 / 2 + 1。
# 7、接下来将 i 的所有数字循环计算即可。

for i in range(1,85):
    if 168 % i==0:
        j= 168/i
        if i>j and (i+j)%2==0 and (i-j)%2==0:
            m = (i+j)/2
            n = (i-j)/2
            x = n**2 - 100
            print("x is equal to: ",format(x)）
            

题目4：输入某年某月某日，判断这一天是这一年的第几天？
year = int(input("Enter the year is :"))
month = int(input("Enter the month is :"))
day = int(input("Enter the day is :"))
days= 0

month_days_1=[31,28,31,30,31,30,31,31,30,31,30,31]
month_days_2=[31,29,31,30,31,30,31,31,30,31,30,31]
if year%400==0 or ((year%4==0) and (year%100!=0)):
    for x in range(0,month-1):
        #range(start, stop[, step])
        # start: 计数从start开始。默认是从0开始。例如range（5）等价于range（0， 5）;
        # stop: 计数到stop结束，但不包括stop。例如：range（0， 5） 是[0, 1, 2, 3, 4]没有5
        days+=month_days_1[x]
    print('This is the {}th day'.format(days+day ))

else:
    for x in range(0,month-1):
        days+=month_days_1[x]
    print('This is the {}th day'.format(days+day))
    

# 题目5：输入三个整数x,y,z，请把这三个数由小到大输出。

num_1=int(input("Enter the first number :"))
num_2=int(input("Enter the second number :"))
num_3=int(input("Enter the third number :"))

numlist=[]

for x in num_1,num_2,num_3:
    numlist.append(x)

numlist.sort()
print(numlist)



 题目6：斐波那契数列。

# 程序分析：斐波那契数列（Fibonacci sequence），又称黄金分割数列，指的是这样一个数列：0、1、1、2、3、5、8、13、21、34、……。
# 在数学上，费波那契数列是以递归的方法来定义：
# F0 = 0     (n=0)
# F1 = 1    (n=1)
# Fn = F[n-1]+ F[n-2](n=>2)

#方法一:定义函数

def fib(n):
    if n==0:
        return [0]
    elif n==1:
        return [0,1]
    elif n==2:
        return [0, 1,1]
    elif n > 2:
        fibs=[0,1,1]
        for x in range(3,n+1):
            fibs.append(fibs[x-1]+fibs[x-2])
        return fibs

n=int(input("Enter :n = "))
print(fib(n))


#方法二：递归函数

def fib(n):
    if n==0:
        return 0
    elif n==1:
        return 1
    elif n==2:
        return 1
    return fib(n-1)+fib(n-2)
n = int(input("Enter :n = "))
print(fib(n))



# 题目7：将一个列表的数据复制到另一个列表中。
# 程序分析：使用列表[:]。

#!/usr/bin/env python3
a=[1,2,3]
b=a*1
print(b)

a=[1,2,3]
b=[]
for x in range(len(a)):
    b.append(a[x])

print(b)

# 题:8：输出 9*9 乘法口诀表。
# 程序分析：分行与列考虑，共9行9列，i控制行，j控制列。

for i in range(1,10):
    print("")
    for j in range(1,i+1):
        print("{}*{}={}  ".format(i,j,i*j),end="")
            


# 题目9：暂停一秒输出。
# 程序分析：使用 time 模块的 sleep() 函数。

import time

t={1:'a',2:'b'}
for x,y in dict.items(t):
    print(x,y)
    time.sleep(1)


# 题目10：暂停一秒输出，并格式化当前时间。
# 程序分析：无

import time

print(time.strftime('%Y-%m-%d %H:%M:%S',time.localtime(time.time())))

#time() 返回当前时间的时间戳（1970纪元后经过的浮点秒数）
# 用法  time.time()

time.sleep(1)
 
print(time.strftime('%Y-%m-%d %H:%M:%S',time.localtime(time.time())))
                  
                  
                  

# 题目11：古典问题：有一对兔子，从出生后第3个月起每个月都生一对兔子，小兔子长到第三个月后每个月又生一对兔子，假如兔子都不死，
# 问每个月的兔子总数为多少？

# 程序分析：兔子的规律为数列1,1,2,3,5,8,13,21..f(n)=f(n-1)+f(n-2)

n=int(input("Enter the number of the month: "))
nums_rabbit=[1,1]

if n==1 or n==2:
    
    nums=2
    
    print('the {}th month,the number of the rabbits is {} .'.format(n,nums))
    
elif n==0:
    
    print('the number of the rabbits is erro .')
      
elif n>2:
    
    print("the 1st month,the number of the rabbits is 2 .")
    print("the 2nd month,the number of the rabbits is 2 .")
    
    for i in range(2,n):
        nums_rabbit.append(nums_rabbit[i-1]+nums_rabbit[i-2])
        
        if i==2:
            print("the {}rd month,the number of the rabbits is {} .".format(i+1,nums_rabbit[i]*2))
        else:
            print('the {}th month,the number of the rabbits is {} .'.format(i+1,nums_rabbit[i]*2))
                  
                  
    

## 题目12：判断101-200之间有多少个素数，并输出所有素数。

# 程序分析：判断素数的方法：用一个数分别去除2到sqrt(这个数)，如果能被整除，则表明此数不是素数，反之是素数。
import numpy as np
import math


nums=[i for i in range(101,201)]
nums_1=[]

for n in nums:
    
    for i in range(2,int(math.sqrt(n))+1):
        if n%i==0:
            nums_1.append(n)
     
    nums_2=np.unique(nums_1)#可以注释掉这一行，因为set集合本身就有去重的功能


    
nums=set(nums)
nums_2=set(nums_2)
nums_3=nums-nums_2  

print('{}\n{}个素数'.format(nums_3,len(nums_3)))
                  
#利用lambda生成器更简单

L = list(filter(lambda x: x not in set([i for i in range(101,201) for j in range(2,i) if not i%j]), range(101,201)))
print('一共有{}个素数，这些素数分别是：{}'.format(len(L),L))
                  
                  
##题目13： 请大家编写一个程序, 重复让用户输入数字； 直到用户输入’i wanna stop’，停止并返回之前数字的个数与总和。

nums = []
sum_nums = 0

while True:
    user_input = input('Please input a number: ')
    
    
    if (user_input != 'I wanna stop') :
        
        nums.append(user_input)
        
    else:
        
        for i in range(len(nums)):
            sum_nums = sum_nums + int(nums[i])
#             print(i,nums[i],sum_nums)

        break
        
print('There are {} numbers and the sum is:{} '.format(len(nums),sum_nums))   
        
print('the program is over.')

                 
                  
