#!/usr/bin/python
# -*- coding: UTF-8 -*

import pandas as pd
import os
import numpy as np


def ELM(Efile_dir):
    
    Enew_filename = Efile_dir + '/E_result.xlsx'

    Efile_list = os.listdir(Efile_dir)
    print("文件夹中有{}个文件".format(len(Efile_list)))
    print('-'*100) 

    E_list=[]
    E = 0

    for file in Efile_list:
        file_path = os.path.join(Efile_dir,file)
        print(file_path)

        df_e = pd.read_excel(file_path,sheet_name=0)
        df_e['地区'] = Efile_list[E]
#         print(df_e.head())
        E = E + 1
        E_list.append(df_e)

    df_E = pd.concat(E_list)
    df_E['地区']=df_E['地区'].str.strip('.xlsx')
    df_E['平台']='饿了么'
    df_E['星选订单号']=df_E['星选订单号'].astype(np.int64)
    df_E['星选订单号']=[' %i' % i for i in df_E['星选订单号']]
    df_E['饿了么订单号']=df_E['饿了么订单号'].astype(np.int64)
    df_E['饿了么订单号']=[' %i' % i for i in df_E['饿了么订单号']]
    
    df_E.to_excel(Enew_filename,index = False)
    print('饿了么数据处理完毕！')
    print('-'*100)
    
 #-------------------------------------------------------------------------------------------------------------   
    
def JD(file_dir):
    
    new_filename = file_dir + '/JD_result.xlsx'

    file_list = os.listdir(file_dir)
    print("文件夹中有{}个文件".format(len(file_list)))
    print('-'*100) 

    new_list=[]
    n = 0

    for file in file_list:
        file_path = os.path.join(file_dir,file)
        print(file_path)

        df_jd = pd.read_excel(file_path,sheet_name='第1页')
        df_jd['地区'] = file_list[n]
        n = n + 1
        new_list.append(df_jd)

    df_jd = pd.concat(new_list)
    df_jd['地区']=df_jd['地区'].str.strip('.xlsx')
    df_jd['平台']='京东到家'
    df_jd = pd.DataFrame(df_jd[['商家id','商家名称','门店id','门店名称','地区','订单号','订单类型','下单时间','完成时间','应结金额','用户支付货款','订单原价','总补贴(平台+商家承担补贴)','平台承担补贴(市场费)','商家承担补贴(货款+运费)','商家承担货款补贴','商家承担运费补贴','商家自送配送费','总佣金(货款佣金+运费佣金+餐盒费佣金)(可开票)','取件服务费(开票)(正向单展示远距离运费;售后单则展示达达售后运费)','商家承担小费','餐盒费','账期','结算单号','结算单状态','结算完成时间','订单序号','关联单号','配送方式','收付款单号','礼品卡费用','订单渠道','用户支付方式','线下收款应结','对账单业务类型','调账原因','平台']])
    df_jd['订单号']=df_jd['订单号'].astype(np.int64)
    df_jd['订单号']=[' %i' % i for i in df_jd['订单号']]
    df_jd['关联单号']=df_jd['关联单号'].astype(np.int64)
    df_jd['关联单号']=[' %i' % i for i in df_jd['关联单号']]
    df_jd.to_excel(new_filename,index = False)

    print('京东数据处理完成！')
    print('-'*100)

# #------------------------------------------------------------------------------------------------------------- 

def MT(file_dir):
    
    new_filename = file_dir + '/MT_result.xlsx'

    file_list = os.listdir(file_dir)
    print("文件夹中有{}个文件".format(len(file_list)))
    print('-'*100) 

    new_list=[]
    n = 0

    for file in file_list:
        file_path = os.path.join(file_dir,file)
        print(file_path)
        df_mt = pd.read_excel(file_path)
        df_mt['地区'] = file_list[n]
        n = n + 1
        new_list.append(df_mt)

    df_mt = pd.concat(new_list)
    df_mt['地区']=df_mt['地区'].str.strip('.xlsx')
    df_mt['平台']='美团'
    
    df_mt['订单号']=df_mt['订单号'].astype(np.int64)
    df_mt['订单号']=[' %i' % i for i in df_mt['订单号']]
    
    df_mt.to_excel(new_filename,index = False)

    print('美团数据处理完成！')
    print('-'*100)
    
    
#------------------------------------------------------------------------------------------------------------- 

E_dir=r'E:/日常数据/账单/20200119/饿百/'#填写文件路径
# JD_dir=r''
MT_dir=r'E:/日常数据/账单/20200119/美团/'

ELM(E_dir) 
# JD(JD_dir)
MT(MT_dir)
