#!/usr/bin/python
# -*- coding: UTF-8 -*

import pandas as pd
import os
import numpy as np


def PJ(PJfile_dir):
    
    PJnew_filename = PJfile_dir + '/对账不平汇总.xlsx'

    PJfile_list = os.listdir(PJfile_dir)
    print("文件夹中有{}个文件".format(len(PJfile_list)))
    print('-'*100) 

    PJ_list=[]
    PJ = 0

    for file in PJfile_list:
        file_path = os.path.join(PJfile_dir,file)
        print(file_path)

        df_DZ = pd.read_excel(file_path,sheet_name=0)

        PJ = PJ + 1
        PJ_list.append(df_DZ)

    df_PJ = pd.concat(PJ_list)
    
    df_PJ['订单号']=df_PJ['订单号'].astype('str')
#     df_PJ['订单号']=['%i ' % i for i in df_PJ['订单号']]
#     
    df_PJ.to_excel(PJnew_filename,index = False)
    print('数据处理完毕！')
    print('-'*100)
    
    
PJ_dir=r'E:/桌面文件夹/作业/'


PJ(PJ_dir) 
